spring:
  thymeleaf:
    cache: false

app:
  edit-path: http://b1665889.ngrok.io/todos/edit

line.bot:
  channel-token: 'Put Channel Token Here.'
  channel-secret: 'Put Channel Token Here.'
  handle-path: /callback

line.login:
  client_id: 'Put Channel Token Here.'
  client_secret: 'Put Channel Token Here.'
  redirect_uri: http://b1665889.ngrok.io/auth