spring:
  thymeleaf:
    cache: false

app:
  edit-path: 'Put Host Name Here'/todos/edit
  cron-exp: 0 0 0,6 * * ?

line.bot:
  channel-token: 'Put Channel Token Here.'
  channel-secret: 'Put Channel Secret Here.'
  handle-path: /callback

line.login:
  client_id: 'Put Channel Client ID Here.'
  client_secret: 'Put Channel Client Secret Here.'
  redirect_uri: 'Put Host Name Here'/auth